spring:
  config:
    activate:
      on-profile: dev

  # --- Banco de Dados Local ---
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticketscale}
    username: ${DB_USERNAME:ticketscale}
    password: ${DB_PASSWORD:ticketscale}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # --- Redis Local ---
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # --- RabbitMQ Local ---
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:ticketscale}
    password: ${RABBITMQ_PASSWORD:ticketscale}
