spring:
  application:
    name: TicketScale
  
  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}

server:
  port: ${PORT:8080}
