spring:
  application:
    name: TicketScale

  threads:
    virtual:
      enabled: true

  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

info:
  app:
    name: ${spring.application.name}
    description: 'Plataforma SaaS para venda e gestão de ingressos'
    java:
      version: ${java.version}
